sudo: required
language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r testthat devtools"
- "./travis-tool.sh install_github jimhester/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- Rscript -e 'library(covr);coveralls()'
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: KmHB2AcGuyI57ivRaipduBs4jeIXI6569sTO7eMKA7e15FtDsmlL8pjlJrjTTp8ipOGjV/3du9oxcktSrFCBo3Hrkl9FHaBeyU1sFb79wjSuVcxkldpP3V6hew9F5PdqUdlwKHvImIyMmeC+cO9zP+rlGJ4/7p02L+7mU7haEXI=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
env:
- global:
  - WARNINGS_ARE_ERRORS=1
  - _R_CHECK_FORCE_SUGGESTS_=0
